### PR TITLE
Add DAI as a base crypto currency

### PR DESCRIPTION
**Pull request by asymmetric**

### CODE REVIEW

**Comment by chubin** [comment]
@asymmetric What about the fullname of DAI?

**Comment by asymmetric** [comment]
Isn't the full name already defined in [lib/coins_names.py](
https://github.com/asymmetric/rate.sx/tree/39b5ddf9ac5160d889c1ce50aa691df0819fdc52/lib/coins_names.py#L536)?

The full name is just Dai, it's not an acronym or anything.

**Comment by asymmetric** [comment]
Any news on this one? :)

**Comment by chubin** [comment]
The currency was added.
Please check.

**Comment by chubin** [comment]
```
$ curl rate.sx/dai

▶ Dai (DAI) ▶ Sat 06 +1d +0.00%


  │                                       1.00
  │ ⡇                                      ⢰⡇                                       
  │ ⡇                                      ⢸⡇                                       
  │ ⡇                                      ⢸⡇                                       
  │ ⡇                                      ⢸⡇                                       
  │ ⡇                                      ⢸⡇                                       
  │ ⡇                                      ⢸⡇                                       
  │ ⡇                                      ⢸⢣       ⢠          ⣀⢀                   
  │ ⡇ ⢀⡄                                   ⢸⢸   ⢰   ⢸         ⣄⣿⣼⡄     ⢠            
  │ ⡇ ⡼⡇                           ⢰⡄      ⢸⢸  ⢸⢸ ⡀⣆⣸        ⡜⢹⡟⠏⡇   ⢸ ⢸            
  │ ⡇ ⡃⡇           ⣴⢰              ⢸⡇      ⢸⢸⢠⢠⣿⣸⡄⡇⣿⡏⡆       ⡇⢸⡇ ⡇  ⣆⡾⡀⡟⡄⡆⢀         
  │ ⣇⢰⠁⡇          ⡄⣿⣿              ⢸⡇⡆     ⣼⢸⢸⣼⡿⣿⣇⢇⡏⡇⡇       ⡇ ⡇ ⡇  ⣿⡇⣿⡇⡇⡇⢸         
  │ ⣿⠉ ⡇        ⢀ ⡇⣿⢹       ⢠⡆     ⢸⣷⡇     ⣿⢸⢸⡏⡇⡇⣿⢸⡇⡇⡇   ⢀⡀ ⢰⡇ ⡇ ⡇ ⢸⢿⡇⢹⡇⡇⡇⣸⡄        
  │ ⡏  ⡇        ⣿⣧⡇⡟⢸ ⣆     ⣿⢿⢠    ⢸⣿⡇     ⡇ ⣿⡇⡇ ⣿⢸⡇⠃⢣   ⡏⡇ ⢸⡇ ⡇ ⡇ ⣼ ⠁ ⡇⢇⣿⣿⡇        
  │ ⡇  ⡇      ⢆ ⡿⢿⡇⡇⢸⢀⣿    ⣰⠁⢸⡜⠄   ⡎⢻⡇     ⡇ ⡇⠇⠃ ⣿⢸⡇ ⢸   ⡇⡇⢀⣾⡇ ⠁ ⠳⣤⡟   ⡇⢸⣿⣿⡇  ⢀     
  │ ⡇  ⡇  ⢀  ⢰⢹ ⡇⠘⠱⡇⢸⣽⣿   ⢰⠙ ⢸⡇⢇ ⢰⢸⡇⠸⡇ ⢀   ⡇ ⡇   ⣟⢸  ⢸ ⡀⣷⡇⣧⢸⡟⡇    ⣿⡅    ⢸⣿⡿⡇  ⢸    ⢀
  │    ⡇ ⢀⣼⡄⢰⢸⢸ ⡇   ⢸⢻⠏⣦  ⢸  ⠘⡇⠈⡇⣾⢸⠃ ⡇⡀⢸   ⡇ ⠁   ⠈⠘  ⢸⣼⣿⠟⡇⣿⣿⡇⡇    ⠙     ⢸⣿⣿⢣⡄ ⣾⢸ ⡄ ⡎
  │    ⡇⢸⡎⠏⣷⣼⢸⢸⣶⡇    ⢸ ⣿  ⡇   ⡇ ⡇⣿⢸  ⡇⣿⣿  ⢀⠇         ⢸⣿⡏  ⣿⣿⠇⡇          ⠘⡿⠸⢸⡇ ⣿⣾⢀⣿⡆⡇
  │    ⡇⣸⡇ ⣿⡏⡇⠈⠈     ⢸ ⣿ ⢠⠃   ⠇ ⣧⠛⣼  ⡇⣿⣿  ⢸          ⢸⡏⡇  ⠁⣿ ⡇           ⠁ ⠘⡇ ⡟⡏⣾⣿⡇⡇
  │    ⢧⣿⡇ ⣿⡇⡇       ⢸ ⡿⡆⢸      ⣿ ⠇  ⢣⣿⡇⡇⣴⢸          ⠈⠃⠃   ⡏                ⢸ ⡇⠁⢿⢿⣿⠇
  │    ⢸⠋⠇ ⠁⠇⡇         ⠃⣿⢸      ⡿    ⢸⣿⠇⡷⢻⢸                ⠁                ⢸⣀⡇ ⢸ ⠻⠁
  │    ⢸     ⠁          ⣿⢸           ⢸⠏⠇  ⣿                                  ⣿⡇     
  │    ⢸                ⡏⡎           ⢸    ⠁                                  ⣿      
  │    ⢸                ⡇                                                    ⠸      
  │    ⢸                ⡇                                                           
  │    ⢸                ⠁                                                           
  │  0.994
  └────────────────────────────────────────────────────────────────────────────────

begin: $0.99820 (Sat 06 20:15) // end: $0.99821 (Sun 07 20:10)
high: $1.0048 (Sun 07 08:15) // low: $0.99367 (Sat 06 21:20)
avg: $0.99847 // median: $0.99925 // change: +4.4475e-06 (+0.00%)
Use @ for interval specification: /btc@10d, /eth@4w, /xrp@January (more in /:help)
```

**Comment by chubin** [comment]
Now I understand.
The PR did not add this, but it is good that you mentioned it.
Now you can use any coin in the domain name (it was not so before).
Thank you for reporting

**Pull request closed without merging**
